import type { Locale } from "../messages"

const pt = {
  teams: "Equipes",
  searchPlayer: "Buscar jogador",
  onlyUnmarked: "Sem spot",
  onlyUnmarkedTitle: "Mostrar só quem ainda não marcou",
  mySpot: "Meu spot",
  mySpotTitle: "Ir para o meu spot",
  allMarked: "Todo mundo já marcou.",
  noneFound: "Nenhum jogador encontrado.",
  noTeams: "Nenhuma equipe no evento ainda.",
  withSpot: "{n}/{total} com spot",
  playersMarked: "jogadores marcados",
  spotOf: "Spot: {label}",
  withoutSpot: "Sem spot",
  share: "Compartilhar",
  shareCopied: "Link copiado",
  readOnlyBadge: "Mapa público",
  fullPage: "Página do evento",
  mapAlt: "Mapa do evento",
  manage: "Gerenciar spots",
  managing: "Gerenciando spots",
  createSpot: "Criar meu spot",
  markingClosed: "Marcações encerradas",
  markingUntil: "Marcações até {date}",
  aimHint: "Arraste o mapa até a mira ficar num canto do seu spot",
  clickHint: "Clique e arraste no mapa para desenhar o seu spot",
  addCorner: "Marcar canto",
  closeRect: "Fechar retângulo",
  panHint: "Segure Shift para mover o mapa",
  tooSmall: "Pequeno demais — arraste um pouco mais",
  tooBig: "Grande demais — marque só onde você cai",
  undo: "Desfazer",
  cancel: "Cancelar",
  confirmSpot: "Confirmar spot",
  leavingFrom: "Ao confirmar, sua equipe sai de {label}.",
  broadcastOn: "Modo transmissão",
  broadcastOff: "Sair do modo transmissão",
  showNames: "Mostrar nomes",
  hideNames: "Esconder nomes",
  zoomIn: "Aumentar",
  zoomOut: "Diminuir",
  fit: "Ver o mapa inteiro",
  legendFree: "Livre",
  legendMine: "Sua equipe",
  legendTaken: "Ocupado",
  legendContested: "Disputado",
  legendMineContested: "Seu spot disputado",
  stateFree: "Livre",
  stateOne: "1 equipe",
  stateMany: "{n} equipes — disputado",
  marked: "Marcado",
  notMarked: "Não marcado",
  placedTitle: "Spot definido",
  placedBody: "Sua equipe está marcada neste spot. Clique em outro spot para trocar.",
  close: "Fechar",
  moveTitle: "Trocar de spot?",
  moveBody: "Sua equipe sai de {from} e passa a estar em {to}.",
  moveConfirm: "Trocar spot",
  releaseTitle: "Desmarcar spot?",
  releaseBody: "Sua equipe sai de {label} e fica sem spot nesta ronda.",
  releasing: "Desmarcando...",
  release: "Desmarcar",
  errorTitle: "Não foi possível",
  gotIt: "Entendi",
  noTeamHere: "Nenhuma equipe neste spot.",
  placeTeamHere: "Colocar equipe aqui",
  moveTo: "Mover para…",
  placeIn: "Colocar em…",
  remove: "Remover",
  removeFromSpot: "Remover do spot",
  saving: "Salvando...",
  staffIn: "Staff · em {label}",
  staffNoSpot: "Staff · sem spot",
  staffState: "Staff · {state}",
  chooseTeam: "Escolher equipe…",
  noOtherTeam: "Nenhuma outra equipe",
  inAnotherSpot: "Em outro spot (move)",
  removedSpot: "spot removido",
  blockAnon: "Você está vendo o mapa em modo leitura. Entre com o Discord para marcar o spot da sua equipe.",
  blockUnverified: "Falta a verificação: você precisa do cargo Verificado no Discord para marcar.",
  blockListOnly: "Só as equipes da lista de classificados marcam neste evento. Você continua vendo o mapa e quem já marcou.",
  blockNotOpen: "Este evento ainda não liberou a marcação.",
  blockRolesList: "Este evento é para quem está na lista de classificados ou tem {roles}. Você continua vendo o mapa e quem já marcou.",
  blockRoles: "Este evento é para quem tem {roles}. Você continua vendo o mapa e quem já marcou.",
  roleOne: "o cargo",
  roleMany: "um dos cargos",
}

const es: typeof pt = {
  teams: "Equipos",
  searchPlayer: "Buscar jugador",
  onlyUnmarked: "Sin spot",
  onlyUnmarkedTitle: "Mostrar solo a quien todavía no marcó",
  mySpot: "Mi spot",
  mySpotTitle: "Ir a mi spot",
  allMarked: "Ya marcaron todos.",
  noneFound: "Ningún jugador encontrado.",
  noTeams: "Todavía no hay equipos en el evento.",
  withSpot: "{n}/{total} con spot",
  playersMarked: "jugadores marcados",
  spotOf: "Spot: {label}",
  withoutSpot: "Sin spot",
  share: "Compartir",
  shareCopied: "Link copiado",
  readOnlyBadge: "Mapa público",
  fullPage: "Página del evento",
  mapAlt: "Mapa del evento",
  manage: "Gestionar spots",
  managing: "Gestionando spots",
  createSpot: "Crear mi spot",
  markingClosed: "Marcaciones cerradas",
  markingUntil: "Marcaciones hasta {date}",
  aimHint: "Arrastra el mapa hasta que la mira quede en una esquina de tu spot",
  clickHint: "Haz clic y arrastra en el mapa para dibujar tu spot",
  addCorner: "Marcar esquina",
  closeRect: "Cerrar rectángulo",
  panHint: "Mantén Shift para mover el mapa",
  tooSmall: "Demasiado chico — arrastra un poco más",
  tooBig: "Demasiado grande — marca solo donde caes",
  undo: "Deshacer",
  cancel: "Cancelar",
  confirmSpot: "Confirmar spot",
  leavingFrom: "Al confirmar, tu equipo sale de {label}.",
  broadcastOn: "Modo transmisión",
  broadcastOff: "Salir del modo transmisión",
  showNames: "Mostrar nombres",
  hideNames: "Ocultar nombres",
  zoomIn: "Acercar",
  zoomOut: "Alejar",
  fit: "Ver el mapa completo",
  legendFree: "Libre",
  legendMine: "Tu equipo",
  legendTaken: "Ocupado",
  legendContested: "Disputado",
  legendMineContested: "Tu spot disputado",
  stateFree: "Libre",
  stateOne: "1 equipo",
  stateMany: "{n} equipos — disputado",
  marked: "Marcado",
  notMarked: "Sin marcar",
  placedTitle: "Spot definido",
  placedBody: "Tu equipo está marcado en este spot. Haz clic en otro spot para cambiar.",
  close: "Cerrar",
  moveTitle: "¿Cambiar de spot?",
  moveBody: "Tu equipo sale de {from} y pasa a estar en {to}.",
  moveConfirm: "Cambiar spot",
  releaseTitle: "¿Desmarcar spot?",
  releaseBody: "Tu equipo sale de {label} y queda sin spot en esta ronda.",
  releasing: "Desmarcando...",
  release: "Desmarcar",
  errorTitle: "No fue posible",
  gotIt: "Entendido",
  noTeamHere: "Ningún equipo en este spot.",
  placeTeamHere: "Colocar equipo aquí",
  moveTo: "Mover a…",
  placeIn: "Colocar en…",
  remove: "Quitar",
  removeFromSpot: "Quitar del spot",
  saving: "Guardando...",
  staffIn: "Staff · en {label}",
  staffNoSpot: "Staff · sin spot",
  staffState: "Staff · {state}",
  chooseTeam: "Elegir equipo…",
  noOtherTeam: "Ningún otro equipo",
  inAnotherSpot: "En otro spot (mueve)",
  removedSpot: "spot quitado",
  blockAnon: "Estás viendo el mapa en modo lectura. Entra con Discord para marcar el spot de tu equipo.",
  blockUnverified: "Falta la verificación: necesitas el rol Verificado en Discord para marcar.",
  blockListOnly: "Solo los equipos de la lista de clasificados marcan en este evento. Puedes seguir viendo el mapa y quién ya marcó.",
  blockNotOpen: "Este evento todavía no habilitó la marcación.",
  blockRolesList: "Este evento es para quien está en la lista de clasificados o tiene {roles}. Puedes seguir viendo el mapa y quién ya marcó.",
  blockRoles: "Este evento es para quien tiene {roles}. Puedes seguir viendo el mapa y quién ya marcó.",
  roleOne: "el rol",
  roleMany: "uno de los roles",
}

export type EventMapCopy = typeof pt

export function eventMapCopy(locale: Locale): EventMapCopy {
  return locale === "es" ? es : pt
}
